apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.jobName }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
  activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
  backoffLimit: {{ .Values.backoffLimit }}
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: bpmn
          emptyDir: {}
        - name: artifact-info
          configMap:
            name: {{ .Values.configMapName }}
        - name: env-secret                    # ← add this
          secret:
            secretName: {{ .Values.secretName }}
      containers:
        - name: downloader
          image: {{ .Values.image }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -eu
              echo "Listing ConfigMap mounted files:"
              ls -la /artifact

              echo "Dumping file contents:"
              for file in /artifact/*; do
                echo "---- $file ----"
                cat "$file"
                echo ""
              done

              if [ -f /artifact/artifactName ]; then
                echo "artifactName: $(cat /artifact/artifactName)"
              fi

              if [ -f /artifact/artifactUrl ]; then
                echo "artifactUrl: $(cat /artifact/artifactUrl)"
              fi

              echo "Done reading ConfigMap"
          volumeMounts:
            - name: bpmn
              mountPath: /bpmn
            - name: artifact-info
              mountPath: /artifact
            - name: env-secret                    # ← add this
              mountPath: /secret
              readOnly: true